dateModified: 1742558253
email:
  fromEmail: lara@likeavirgin.be
  fromName: Magma
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    0ed89233-3149-4024-8b54-cf1dfa257ed1: Magma # Magma
    f27a3297-646a-4d42-be78-9128a387ea1c: Magma # Magma
system:
  edition: solo
  live: true
  name: Magma
  schemaVersion: 5.6.0.2
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
